import os

from requests import request, Response
from dotenv import load_dotenv

load_dotenv()

telegram_bot_credential = os.environ["BOT_ID_TELEGRAM"]  # Generated by Bot Father
group_id = os.environ["GROUP_ID_TELEGRAM"]  # telegram group id


def send_message_to_telegram(message) -> Response:
    try:
        url = "https://api.telegram.org/bot" + str(telegram_bot_credential) + "/sendMessage?chat_id=" + str(group_id)

        text_data = {"text": message}
        response = request("POST", url, params=text_data)

        return response
    except Exception as error:
        message = str(error) + ": Exception occur in send_message_to_telegram"
        print(message)
