import os

from requests import request, Response
from dotenv import load_dotenv

load_dotenv()

telegram_bot_credential = os.environ["BOT_ID_TELEGRAM"]  # Generated by Bot Father
group_id = os.environ["GROUP_ID_TELEGRAM"]  # telegram group id


def send_message_to_telegram(message: str) -> Response:
    """
    Sends a message to a Telegram group using the Telegram Bot API.

    Parameters:
    - message (str): The text message to be sent to the Telegram group.

    Returns:
    - Response: The response object received from the Telegram API after attempting to send the message.

    Raises:
    - Exception: If an error occurs during the execution, an exception is caught and an error message is printed.

    Note:
    - This function relies on environment variables for Telegram bot credentials (`BOT_ID_TELEGRAM`) and the Telegram group ID (`GROUP_ID_TELEGRAM`).
    - Make sure to load the environment variables using `load_dotenv()` before calling this function.
    """
    try:
        url = "https://api.telegram.org/bot" + str(telegram_bot_credential) + "/sendMessage?chat_id=" + str(group_id)

        text_data = {"text": message}
        response = request("POST", url, params=text_data)

        return response
    except Exception as error:
        message = str(error) + ": Exception occur in send_message_to_telegram"
        print(message)
